package nyc.c4q.buzzfeedquizapp;

import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import java.util.List;

/**
 * Created by MsNehisi on 11/14/17.
 */

public class ColorAdapter extends RecyclerView.Adapter {

    private List<Question> questions;

    // Type is an Object and the Object is Question in this example
    public ColorAdapter (List<Question> questions) {
        // Empty constructor at first then updated with the below
        this.questions = questions;
    }
    // Gets viewgroup of the parent - this is what the layout is going to attach to which will give you access to be passed to next method.
    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        //This can be done within our view holder class itself but you will also see the layout defined in the adapter as such
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.color_viewholder, parent, false);

        //The view is then passed to an instance of our CustomViewHolder
        return new ColorViewHolder(view);
    }

    // Passes the view holder created by adapter and the position (zero indexed to n (list.size))
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        ColorViewHolder colorViewHolder = (ColorViewHolder) holder;
        colorViewHolder.bind(questions.get(position));

    }
    // Returns # of RecyclerView. if out of bounds then it will crash.
    @Override
    public int getItemCount() {
//        return 0; // generated by Android Studio for the method then updated below
        return questions.size();
    }
}